name: relax_sounds
description: A relaxing sounds app with multiple languages support.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  just_audio: ^0.10.2
  google_mobile_ads: ^6.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  flutter_svg: ^2.0.9
  intl: ^0.19.0
  in_app_purchase: ^3.1.13
  path_provider: ^2.1.2
  flutter_native_splash: ^2.3.10
  url_launcher: ^6.2.4
  volume_controller: ^2.0.8
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.0.2
  audio_service: ^0.18.18
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon.png"

flutter_native_splash:
  color: "#000000"
  image: assets/icons/splash.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/icons/splash.png
    icon_background_color: "#000000"
  fullscreen: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill
  image_dark: assets/icons/splash.png
  color_dark: "#000000"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - .env 